import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Access Log Control",
  description: "Generated by create-t3-app and me :)",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const username = "jcinybulk"

function Header(){

  return(
    <nav className="flex flex-row justify-between items-center w-full border-b p-4">
      <div className="font-bold text-2xl">Správa přístupů</div>
      <div className="flex flex-row justify-between gap-4">
        <div>Přehled uživatelů</div>
        <div>Správa rolí</div>
        <div>Admin</div>
        <div className="font-bold">{username}</div>        
      </div>

    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="">
        <div className="h-screen flex flex-col">
          <Header/>
          <main className="flex-1 overflow-hidden flex w-full justify-center">{children}</main>
        </div>
      </body>
    </html>
  );
}
