import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Access Log Control",
  description: "Generated by create-t3-app and me :)",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

function Header(){

  return(
    <nav className="flex flex-row justify-between xl w-full border-b p-4">Ahoj</nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="">
        <div className="h-screen flex flex-col">
          <Header/>
          <main className="flex-1 overflow-hidden flex w-full justify-center">{children}</main>
        </div>
      </body>
    </html>
  );
}
